# -*- coding: utf-8 -*-
"""unit6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TLjdeP28uGgfz4YeR7PF8o7d65QiZFe4

# Unit 6. 변수와 입력

## 6.1 변수
- 영문 문자와 숫자를 사용할 수 있습니다.
- 대소문자를 구분합니다.
- 문자부터 시작해야 하며 숫자부터 시작하면 안 됩니다.
- _(밑줄 문자)로 시작할 수 있습니다.
- 특수 문자(+, -, *, /, $, @, &, % 등)는 사용할 수 없습니다.
- 파이썬의 키워드(if, for, while, and, or 등)는 사용할 수 없습니다.
"""

# 할당 Assignment
x = 10
x

s = 'Fucking'
s

type(x), type(s)

x, y, z = 10, 30 , 50
x, y, z

del x, y, z

x = None
print(x)

"""## 6.2 변수"""

a = 10
a = a + 10
a

b = 10
b += 10
b

sum = 0
proc = 1
for i in range(1,11):
  sum += i
  proc*= i
sum, proc

-proc

input()

a = input()
print(a)

x = input('하고 싶은 말을 적어보세요')
x

del x, a, sum, proc

var1 = int(input('첫번째 정수'))
var2 = int(input('두번째 정수'))
var1 + var2

"""## 6.4 입력값 두개"""

c = 'Gook bye my friend'
c.split()
c1, c2, c3, c4 =c.split()
c1, c2, c3, c4

a, b=input('정수 두개 입력>').split()

a = int(a)
b = int(b)
a+b

"""### map"""

a, b =map(int, input().split())

a+b

import math
a, b = map(math.sqrt,[5 , 15])
a, b

